            - name: Setup Jira
  # You may pin to the exact commit or the version.
  # uses: atlassian/gajira-cli@7b8487d76cd88bf5d50ba00c6cca6edff1ddd507
  uses: atlassian/gajira-cli@v3
  with:
    # Version of the CLI to use
    version: # optional, default is 1.0.27
          
